baseURL = "https://kurtmitman.github.io/"
languageCode = "en-us"
title = "Kurt Mitman"
theme = "PaperMod"
[pagination]
  pagerSize = 10

[params]
  author = "Kurt Mitman"
  ShowShareButtons = false
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
[[menu.main]]
  name = "Research"
  url = "/research"
  weight = 1

[[menu.main]]
  name = "CV"
  url = "/KurtMitmanCV.pdf"
  weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
