
baseURL = "https://kurtmitman.com/"
languageCode = "en-us"
title = "Kurt Mitman"
theme = "PaperMod"
enableRobotsTXT = true
publishDir = "docs"

[params]
  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"
